name: notustohtml
description: Convert the Notus document format to an HTML representation.
version: 0.0.9-dev.3.0
homepage: https://github.com/JacobWrenn/notustohtml

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  notus: ^1.0.0-dev
  flutter_quill:
    git:
      url: https://github.com/SedlarDavid/flutter-quill.git
  html: ^0.15.0

dev_dependencies:
  test:
